name: Publish package
on:
  create:
  workflow_dispatch:
    inputs:
      npm: 
        description: 'Publish to npm'
        required: false
        default: 'true'
      github: 
        description: 'Publish to GitHub'
        required: false
        default: 'true'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      github.event.inputs.npm == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          always-auth: true
          registry-url: "https://registry.npmjs.org"
          scope: "@myalbum"
      - name: Node modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build
      - name: Setup git
        run: |
          git config --local user.email "sysadmin@myalbum.com"
          git config --local user.name "MyAlbum System"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  publish-github:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      github.event.inputs.github == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@myalbum"
      - name: Node modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build
      - name: Setup git
        run: |
          git config --local user.email "sysadmin@myalbum.com"
          git config --local user.name "MyAlbum System"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}